class AppLocalization {
  static const Map<String, Map<String, String>> translations = {
    'en': {
      'app_title': 'NoSkipAI',
      'login_title': 'Welcome Back',
      'login_subtitle': 'Sign in to your account',
      'register_title': 'Create Account',
      'register_subtitle': 'Join millions taking medications on time',
      'email': 'Email',
      'password': 'Password',
      'confirm_password': 'Confirm Password',
      'first_name': 'First Name',
      'last_name': 'Last Name',
      'phone_number': 'Phone Number',
      'sign_in': 'Sign In',
      'sign_up': 'Sign Up',
      'forgot_password': 'Forgot Password?',
      'dont_have_account': 'Don\'t have an account?',
      'already_have_account': 'Already have an account?',
      'dashboard': 'Dashboard',
      'medications': 'Medications',
      'chat': 'Chat',
      'settings': 'Settings',
      'today': 'Today',
      'this_week': 'This Week',
      'this_month': 'This Month',
      'adherence_rate': 'Adherence Rate',
      'add_medication': 'Add Medication',
      'medication_name': 'Medication Name',
      'dosage': 'Dosage',
      'frequency': 'Frequency',
      'schedule': 'Schedule',
      'mark_taken': 'Mark as Taken',
      'mark_missed': 'Mark as Missed',
      'ai_assistant': 'AI Assistant',
      'type_message': 'Type your message...',
      'language': 'Language',
      'dark_mode': 'Dark Mode',
      'notifications': 'Notifications',
      'about': 'About',
      'logout': 'Logout',
      'error': 'Error',
      'success': 'Success',
      'loading': 'Loading...',
      'retry': 'Retry',
      'no_medications': 'No medications added yet',
      'add_first_medication': 'Add your first medication to get started',
    },
    'uz': {
      'app_title': 'NoSkipAI',
      'login_title': 'Xush kelibsiz',
      'login_subtitle': 'Hisobingizga kiring',
      'register_title': 'Hisob yaratish',
      'register_subtitle': 'Milyonlab odamga qo\'shiling davolarni o\'z vaqtida qabul qiluvchilar',
      'email': 'Email',
      'password': 'Parol',
      'confirm_password': 'Parolni tasdiqlang',
      'first_name': 'Ismi',
      'last_name': 'Familiyasi',
      'phone_number': 'Telefon raqami',
      'sign_in': 'Kirish',
      'sign_up': 'Ro\'yxatdan o\'tish',
      'forgot_password': 'Parolni unutdingizmi?',
      'dont_have_account': 'Hisobingiz yo\'qmi?',
      'already_have_account': 'Allaqachon hisobingiz bormi?',
      'dashboard': 'Bosh sahifa',
      'medications': 'Dorilar',
      'chat': 'Chat',
      'settings': 'Sozlamalar',
      'today': 'Bugun',
      'this_week': 'Bu hafta',
      'this_month': 'Bu oy',
      'adherence_rate': 'Rioya qilish stavkasi',
      'add_medication': 'Dori qo\'shish',
      'medication_name': 'Dori nomi',
      'dosage': 'Doza',
      'frequency': 'Chastotasi',
      'schedule': 'Jadval',
      'mark_taken': 'Qabul qilingan deb belgilash',
      'mark_missed': 'O\'tkazilgan deb belgilash',
      'ai_assistant': 'AI yordamchi',
      'type_message': 'Xabar yozing...',
      'language': 'Til',
      'dark_mode': 'Qorong\'i rejim',
      'notifications': 'Bildirishnomalar',
      'about': 'Haqida',
      'logout': 'Chiqish',
      'error': 'Xato',
      'success': 'Muvaffaqiyat',
      'loading': 'Yuklanmoqda...',
      'retry': 'Qayta urinish',
      'no_medications': 'Dorilar qo\'shilmagan',
      'add_first_medication': 'Boshlash uchun birinchi dori qo\'shing',
    },
    'ru': {
      'app_title': 'NoSkipAI',
      'login_title': 'С возвращением',
      'login_subtitle': 'Войдите в свой аккаунт',
      'register_title': 'Создать аккаунт',
      'register_subtitle': 'Присоединитесь к миллионам, принимающим лекарства вовремя',
      'email': 'Электронная почта',
      'password': 'Пароль',
      'confirm_password': 'Подтвердить пароль',
      'first_name': 'Имя',
      'last_name': 'Фамилия',
      'phone_number': 'Номер телефона',
      'sign_in': 'Войти',
      'sign_up': 'Зарегистрироваться',
      'forgot_password': 'Забыли пароль?',
      'dont_have_account': 'Нет аккаунта?',
      'already_have_account': 'Уже есть аккаунт?',
      'dashboard': 'Панель управления',
      'medications': 'Лекарства',
      'chat': 'Чат',
      'settings': 'Параметры',
      'today': 'Сегодня',
      'this_week': 'На этой неделе',
      'this_month': 'В этом месяце',
      'adherence_rate': 'Уровень соблюдения',
      'add_medication': 'Добавить лекарство',
      'medication_name': 'Название лекарства',
      'dosage': 'Дозировка',
      'frequency': 'Частота',
      'schedule': 'Расписание',
      'mark_taken': 'Отметить как принято',
      'mark_missed': 'Отметить как пропущено',
      'ai_assistant': 'ИИ-ассистент',
      'type_message': 'Введите сообщение...',
      'language': 'Язык',
      'dark_mode': 'Темный режим',
      'notifications': 'Уведомления',
      'about': 'О приложении',
      'logout': 'Выход',
      'error': 'Ошибка',
      'success': 'Успех',
      'loading': 'Загрузка...',
      'retry': 'Повторить',
      'no_medications': 'Лекарства не добавлены',
      'add_first_medication': 'Добавьте первое лекарство, чтобы начать',
    }
  };

  static String translate(String key, String locale) {
    return translations[locale]?[key] ?? key;
  }
}
